### ISSUE TITLE
Tiny improvement to increase readability

### ISSUE THREAD

**Issue by leandermelms** [nltk/nltk_book#178]
I really enjoyed reading this book. However, I noticed that the readability could be easily improved by adding: 

```css
p {
    font-size: 18px;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
    line-height: 1.5;
}


.document {
    max-width: 980px;
    margin: 0 auto;
}
```

I've injected this into the site and thought that this might be useful to others. This, at least, works well on a 13inch screen.
